export const ADD_FAVORITE_TERM = 'ADD_FAVORITE_TERM';
export const REMOVE_FAVORITE_TERM = 'REMOVE_FAVORITE_TERM';
export const ADD_FETCHED_DATA = 'ADD_FETCHED_DATA';

export const API = "API";
export const API_START = "API_START";
export const API_END = "API_END";
export const ACCESS_DENIED = "ACCESS_DENIED";
export const API_ERROR = "API_ERROR";

export const SELECT_STORE = 'SELECT_STORE';
// export const CACHE_STORE_LOCATIONS = 'CACHE_STORE_LOCATIONS';
// export const CACHE_STORE_PROFILE = 'CACHE_STORE_PROFILE';
export const CACHE_STORES_DATA = 'CACHE_STORES_DATA';
export const SELECT_CURRENT_FUNCTION = 'SELECT_CURRENT_FUNCTION';

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

/* Display profiles */
export const SELECT_LOGIN_DISPLAY = "SELECT_LOGIN_DISPLAY";
export const SELECT_STORE_SELECTION_DISPLAY = "SELECT_STORE_SELECTION_DISPLAY";
export const SELECT_STORE_FUNCTIONALITIES_DISPLAY = "SELECT_STORE_FUNCTIONALITIES_DISPLAY";
export const SELECT_STORE_POS_DISPLAY = "SELECT_STORE_POS_DISPLAY";